###Listar habitos do usuário
GET http://localhost:5000/api/habitos/usuario/1

###Cadastrar usuário
POST http://localhost:5000/api/usuario/cadastrar
Content-Type: application/json

{
    "Nome": "Lucas",
    "Email": "lucas@gmail.com",
    "Senha": "123"
}

###Cadastrar habitos
POST http://localhost:5000/api/habitos/cadastrar
Content-Type: application/json

{
    "Nome": "Ler",
    "Descricao": "Ler 10 pgs",
    "UsuarioId": 1
}

###Deletar habitos
DELETE http://localhost:5000/api/habitos/deletar/2

###alterar habitos
PATCH http://localhost:5000/api/habitos/alterar/2
Content-Type: application/json

{
    "Nome": "Ler",
    "Descricao": "Ler 20 pgs"
}

###Marcar hábito como concluido
POST http://localhost:5000/api/registros
Content-Type: application/json

{
    "HabitoId": 2
}

###Ver streak do usuario
GET http://localhost:5000/api/usuarios/1/streaks

###Login do usuario
POST http://localhost:5000/api/usuario/login
Content-Type: application/json

{
    "Email": "lucas@gmail.com",
    "Senha": "123"
}