#teste cadastro de usuario
POST http://localhost:5000/usuario/cadastrar
Content-Type: application/json

{
  "Nome": "Lucas Alves",
  "Email": "lucas.alves@gmail.com",
  "Senha": "12345"
}

###
#teste login de usuario
POST http://localhost:5000/usuario/login
Content-Type: application/json

{
  "email": "lucas.alves@gmail.com",
  "senha": "1245"
}